import type { Metadata } from "next";
import { Inter } from 'next/font/google'
import "./globals.css";

const geistSans = Inter({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Inter({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: {
    absolute: "",
    default: "Next.js Tutorial - By Madhawa",
    template: "%s | By Madhawa"
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header style={{
            backgroundColor: "lightblue",
            padding: "1rem"
          }}>
          <p>Header</p>
        </header>
        {children}

        <footer style={{
          backgroundColor: "ghostWhite",
          padding: "1rem"
        }}>
          <p>Footer</p>

        </footer>
      </body>
    </html>
  );
}
